name = "taima-alwani"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "taima-alwani-db"
database_id = "1cc63f9d-3cdc-4f36-9514-9412f9276146"
